### ISSUE TITLE
This should be a package on the racket package catalog 

### ISSUE THREAD

**Issue by spdegabrielle** [xandkar/gg#1]
This should be a package on the racket package catalog 
let me know if you need help - it is tricky the first time

**Comment by xandkar** [comment]
I'll take time to package it up at the end of the week and will certainly ping you if issues come up. Thanks @spdegabrielle !

**Comment by xandkar** [comment]
@spdegabrielle added some package data to the repo and created one here: https://pkgd.racket-lang.org/pkgn/package/gg

Waiting for the next index rebuild.

Does this looks reasonable? https://github.com/xandkar/gg/commit/d8daddde512bba0cd6e9497a53b52cf70d624449

**Comment by spdegabrielle** [comment]
Looks great. Go for it!

**Comment by xandkar** [comment]
Confirmed that the package was indexed and local install worked. Thanks for the push!
